In [1]:
# importing essential libraries
import pandas as pd
import numpy as np
import os
import warnings
from pandasql import sqldf

In [2]:
# supressing warning messages
warnings.filterwarnings('ignore')

In [3]:
# locating the data
parent_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
data_path = os.path.join(parent_dir,"data","test.csv")

#loading the data
df = pd.read_csv(data_path)
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16457E+15,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [ ]:
# looking at available features
df.columns.to_list()

In [24]:
# calculating percentages of missing values in each column 
def calculateMissing(df):
    df2 = df.isna().sum().to_frame().reset_index()
    df2.rename(columns = {'index':'variables', 0:'count'}, inplace = True)
    df2['percent'] = round(df2['count']*100/df.shape[0])
    print(df2)

calculateMissing(df)

                                   variables   count  percent
0                                  Bearer Id       0      0.0
1                                      Start       1      0.0
2                                   Start ms       1      0.0
3                                        End       1      0.0
4                                     End ms       1      0.0
5                                  Dur. (ms)       1      0.0
6                                       IMSI       0      0.0
7                              MSISDN/Number    1066      1.0
8                                       IMEI     572      0.0
9                         Last Location Name    1153      1.0
10                           Avg RTT DL (ms)   27829     19.0
11                           Avg RTT UL (ms)   27812     19.0
12                   Avg Bearer TP DL (kbps)       1      0.0
13                   Avg Bearer TP UL (kbps)       1      0.0
14               TCP DL Retrans. Vol (Bytes)   88146     59.0
15               TCP UL Retrans. Vol (Bytes)   96649     64.0
16                       DL TP < 50 Kbps (%)     754      1.0
17            50 Kbps < DL TP < 250 Kbps (%)     754      1.0
18             250 Kbps < DL TP < 1 Mbps (%)     754      1.0
19                        DL TP > 1 Mbps (%)     754      1.0
20                       UL TP < 10 Kbps (%)     792      1.0
21             10 Kbps < UL TP < 50 Kbps (%)     792      1.0
22            50 Kbps < UL TP < 300 Kbps (%)     792      1.0
23                      UL TP > 300 Kbps (%)     792      1.0
24                           HTTP DL (Bytes)   81474     54.0
25                           HTTP UL (Bytes)   81810     55.0
26                 Activity Duration DL (ms)       1      0.0
27                 Activity Duration UL (ms)       1      0.0
28                               Dur. (ms).1       1      0.0
29                      Handset Manufacturer     572      0.0
30                              Handset Type     572      0.0
31           Nb of sec with 125000B < Vol DL   97538     65.0
32     Nb of sec with 1250B < Vol UL < 6250B   92894     62.0
33  Nb of sec with 31250B < Vol DL < 125000B   93586     62.0
34            Nb of sec with 37500B < Vol UL  130254     87.0
35    Nb of sec with 6250B < Vol DL < 31250B   88317     59.0
36    Nb of sec with 6250B < Vol UL < 37500B  111843     75.0
37             Nb of sec with Vol DL < 6250B     755      1.0
38             Nb of sec with Vol UL < 1250B     793      1.0
39                   Social Media DL (Bytes)       0      0.0
40                   Social Media UL (Bytes)       0      0.0
41                         Google DL (Bytes)       0      0.0
42                         Google UL (Bytes)       0      0.0
43                          Email DL (Bytes)       0      0.0
44                          Email UL (Bytes)       0      0.0
45                        Youtube DL (Bytes)       0      0.0
46                        Youtube UL (Bytes)       0      0.0
47                        Netflix DL (Bytes)       0      0.0
48                        Netflix UL (Bytes)       0      0.0
49                         Gaming DL (Bytes)       0      0.0
50                         Gaming UL (Bytes)       0      0.0
51                          Other DL (Bytes)       0      0.0
52                          Other UL (Bytes)       0      0.0
53                          Total UL (Bytes)       1      0.0
54                          Total DL (Bytes)       1      0.0

In [25]:
#droping columns with more than 30% missing values.
df3 = df.drop(df.columns[[14, 15, 24, 25, 31, 32, 33, 34, 35, 36]], axis=1) 
df3.shape

(150001, 45)

In [26]:
#checking data types of variables to decide how to handle missing values
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 45 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Bearer Id                       150001 non-null  object
 1   Start                           150000 non-null  object
 2   Start ms                        150000 non-null  float64
 3   End                             150000 non-null  object
 4   End ms                          150000 non-null  float64
 5   Dur. (ms)                       150000 non-null  float64
 6   IMSI                            150001 non-null  object
 7   MSISDN/Number                   148935 non-null  float64
 8   IMEI                            149429 non-null  float64
 9   Last Location Name              148848 non-null  object
 10  Avg RTT DL (ms)                 122172 non-null  float64
 11  Avg RTT UL (ms)                 122189 non-null  float64
 12  Avg Bearer TP DL (kbps)         150000 non-null  float64
 13  Avg Bearer TP UL (kbps)         150000 non-null  float64
 14  DL TP < 50 Kbps (%)             149247 non-null  float64
 15  50 Kbps < DL TP < 250 Kbps (%)  149247 non-null  float64
 16  250 Kbps < DL TP < 1 Mbps (%)   149247 non-null  float64
 17  DL TP > 1 Mbps (%)              149247 non-null  float64
 18  UL TP < 10 Kbps (%)             149209 non-null  float64
 19  10 Kbps < UL TP < 50 Kbps (%)   149209 non-null  float64
 20  50 Kbps < UL TP < 300 Kbps (%)  149209 non-null  float64
 21  UL TP > 300 Kbps (%)            149209 non-null  float64
 22  Activity Duration DL (ms)       150000 non-null  float64
 23  Activity Duration UL (ms)       150000 non-null  float64
 24  Dur. (ms).1                     150000 non-null  float64
 25  Handset Manufacturer            149429 non-null  object
 26  Handset Type                    149429 non-null  object
 27  Nb of sec with Vol DL < 6250B   149246 non-null  float64
 28  Nb of sec with Vol UL < 1250B   149208 non-null  float64
 29  Social Media DL (Bytes)         150001 non-null  float64
 30  Social Media UL (Bytes)         150001 non-null  float64
 31  Google DL (Bytes)               150001 non-null  float64
 32  Google UL (Bytes)               150001 non-null  float64
 33  Email DL (Bytes)                150001 non-null  float64
 34  Email UL (Bytes)                150001 non-null  float64
 35  Youtube DL (Bytes)              150001 non-null  float64
 36  Youtube UL (Bytes)              150001 non-null  float64
 37  Netflix DL (Bytes)              150001 non-null  float64
 38  Netflix UL (Bytes)              150001 non-null  float64
 39  Gaming DL (Bytes)               150001 non-null  float64
 40  Gaming UL (Bytes)               150001 non-null  float64
 41  Other DL (Bytes)                150001 non-null  float64
 42  Other UL (Bytes)                150001 non-null  float64
 43  Total UL (Bytes)                150000 non-null  float64
 44  Total DL (Bytes)                150000 non-null  float64
dtypes: float64(38), object(7)
memory usage: 51.5+ MB

In [27]:
#filling missing values of categorical variables with mode 
df3['Handset Type'] = df3['Handset Type'].fillna(df3['Handset Type'].mode()[0])
df3['Bearer Id'] = df3['Bearer Id'].fillna(df3['Bearer Id'].mode()[0])
df3['IMSI'] = df3['IMSI'].fillna(df3['IMSI'].mode()[0])
df3['Handset Manufacturer'] = df3['Handset Manufacturer'].fillna(df3['Handset Manufacturer'].mode()[0])

In [28]:
#filling missing average RTT DL and UL values with the median value
df3['Avg RTT DL (ms)'] = df3['Avg RTT DL (ms)'].fillna(df3['Avg RTT DL (ms)'].median())
df3['Avg RTT UL (ms)'] = df3['Avg RTT UL (ms)'].fillna(df3['Avg RTT UL (ms)'].median())

In [29]:
calculateMissing(df3)

                         variables  count  percent
0                        Bearer Id      0      0.0
1                            Start      1      0.0
2                         Start ms      1      0.0
3                              End      1      0.0
4                           End ms      1      0.0
5                        Dur. (ms)      1      0.0
6                             IMSI      0      0.0
7                    MSISDN/Number   1066      1.0
8                             IMEI    572      0.0
9               Last Location Name   1153      1.0
10                 Avg RTT DL (ms)      0      0.0
11                 Avg RTT UL (ms)      0      0.0
12         Avg Bearer TP DL (kbps)      1      0.0
13         Avg Bearer TP UL (kbps)      1      0.0
14             DL TP < 50 Kbps (%)    754      1.0
15  50 Kbps < DL TP < 250 Kbps (%)    754      1.0
16   250 Kbps < DL TP < 1 Mbps (%)    754      1.0
17              DL TP > 1 Mbps (%)    754      1.0
18             UL TP < 10 Kbps (%)    792      1.0
19   10 Kbps < UL TP < 50 Kbps (%)    792      1.0
20  50 Kbps < UL TP < 300 Kbps (%)    792      1.0
21            UL TP > 300 Kbps (%)    792      1.0
22       Activity Duration DL (ms)      1      0.0
23       Activity Duration UL (ms)      1      0.0
24                     Dur. (ms).1      1      0.0
25            Handset Manufacturer      0      0.0
26                    Handset Type      0      0.0
27   Nb of sec with Vol DL < 6250B    755      1.0
28   Nb of sec with Vol UL < 1250B    793      1.0
29         Social Media DL (Bytes)      0      0.0
30         Social Media UL (Bytes)      0      0.0
31               Google DL (Bytes)      0      0.0
32               Google UL (Bytes)      0      0.0
33                Email DL (Bytes)      0      0.0
34                Email UL (Bytes)      0      0.0
35              Youtube DL (Bytes)      0      0.0
36              Youtube UL (Bytes)      0      0.0
37              Netflix DL (Bytes)      0      0.0
38              Netflix UL (Bytes)      0      0.0
39               Gaming DL (Bytes)      0      0.0
40               Gaming UL (Bytes)      0      0.0
41                Other DL (Bytes)      0      0.0
42                Other UL (Bytes)      0      0.0
43                Total UL (Bytes)      1      0.0
44                Total DL (Bytes)      1      0.0

In [30]:
# droping all other rows with missing values. becuase they are equal to or less than 1%.
df3.dropna(inplace=True)
calculateMissing(df3)

                         variables  count  percent
0                        Bearer Id      0      0.0
1                            Start      0      0.0
2                         Start ms      0      0.0
3                              End      0      0.0
4                           End ms      0      0.0
5                        Dur. (ms)      0      0.0
6                             IMSI      0      0.0
7                    MSISDN/Number      0      0.0
8                             IMEI      0      0.0
9               Last Location Name      0      0.0
10                 Avg RTT DL (ms)      0      0.0
11                 Avg RTT UL (ms)      0      0.0
12         Avg Bearer TP DL (kbps)      0      0.0
13         Avg Bearer TP UL (kbps)      0      0.0
14             DL TP < 50 Kbps (%)      0      0.0
15  50 Kbps < DL TP < 250 Kbps (%)      0      0.0
16   250 Kbps < DL TP < 1 Mbps (%)      0      0.0
17              DL TP > 1 Mbps (%)      0      0.0
18             UL TP < 10 Kbps (%)      0      0.0
19   10 Kbps < UL TP < 50 Kbps (%)      0      0.0
20  50 Kbps < UL TP < 300 Kbps (%)      0      0.0
21            UL TP > 300 Kbps (%)      0      0.0
22       Activity Duration DL (ms)      0      0.0
23       Activity Duration UL (ms)      0      0.0
24                     Dur. (ms).1      0      0.0
25            Handset Manufacturer      0      0.0
26                    Handset Type      0      0.0
27   Nb of sec with Vol DL < 6250B      0      0.0
28   Nb of sec with Vol UL < 1250B      0      0.0
29         Social Media DL (Bytes)      0      0.0
30         Social Media UL (Bytes)      0      0.0
31               Google DL (Bytes)      0      0.0
32               Google UL (Bytes)      0      0.0
33                Email DL (Bytes)      0      0.0
34                Email UL (Bytes)      0      0.0
35              Youtube DL (Bytes)      0      0.0
36              Youtube UL (Bytes)      0      0.0
37              Netflix DL (Bytes)      0      0.0
38              Netflix UL (Bytes)      0      0.0
39               Gaming DL (Bytes)      0      0.0
40               Gaming UL (Bytes)      0      0.0
41                Other DL (Bytes)      0      0.0
42                Other UL (Bytes)      0      0.0
43                Total UL (Bytes)      0      0.0
44                Total DL (Bytes)      0      0.0

In [31]:
# counting unique users
print(len(pd.unique(df3['MSISDN/Number'])))
print(df3.shape)

105719
(146891, 45)

In [32]:
# removing duplicate users
df3 = df3.drop_duplicates(subset='MSISDN/Number', keep='first')
print(df3.shape)

(105719, 45)

<h1>Querying using sql</h1>

In [13]:
# creating a querying function.
queryDf = lambda q: sqldf(q, globals())

In [ ]:
def getTopHandsets(num):
    query = 'SELECT "Handset Type", count(*) as user_count FROM df3 WHERE "Handset Type" != "undefined" group by "Handset Type" order by user_count DESC LIMIT '+str(num)
    return queryDf(query)

print(getTopHandsets(10))

In [ ]:
def getTopManu(num):
    query = 'SELECT "Handset Manufacturer", count(*) as user_count FROM df3 WHERE "Handset Type" != "undefined" group by "Handset Manufacturer" order by user_count DESC LIMIT '+str(num)
    return queryDf(query)
print(getTopManu(3))

In [ ]:
def manByHandset(lis, dfname):
    for man in lis:
        query = 'SELECT "Handset Manufacturer", "Handset Type", count(*) as num_users \
        FROM '+dfname+'\
        WHERE "Handset Manufacturer" = "'+man+'" \
        group by "Handset Type" \
        order by num_users DESC \
        LIMIT 3'
        print(queryDf(query),'\n')

manByHandset(getTopManu(5)["Handset Manufacturer"].to_list(),'df3')

In [ ]:
len(pd.unique(df['Handset Type']))

In [22]:
def find_agg(df, group_columns, agg_columns, agg_metrics, new_columns):
    new_column_dict ={}
    agg_dict = {}
    for i in range(len(agg_columns)):
        new_column_dict[agg_columns[i]] = new_columns[i]
        agg_dict[agg_columns[i]] = agg_metrics[i]

    new_df = df.groupby(group_columns).agg(agg_dict).reset_index().rename(columns=new_column_dict)
    return new_df

grouping_lis = ["MSISDN/Number"]
aggr_lis = ["Bearer Id", "Dur. (ms)", "Total DL (Bytes)", "Total UL (Bytes)", "Social Media DL (Bytes)", "Social Media UL (Bytes)",\
    "Youtube DL (Bytes)", "Youtube UL (Bytes)"] 
metric_lis = ["count", "sum", "sum", "sum", "sum", "sum", "sum", "sum"]
col_names = ["xDr_session_count", "session_dur", "Total_DL_sum", "Total_UL_sum", "Social_Media_DL_sum", "Social_Media_UL_sum",\
    "Youtube_DL_sum", "Youtube_UL_sum"]
print(find_agg(df, grouping_lis, aggr_lis, metric_lis, col_names).head())

   MSISDN/Number  xDr_session_count  session_dur  Total_DL_sum  Total_UL_sum  \
0   3.360100e+10                  1     116720.0  8.426375e+08    36053108.0
1   3.360100e+10                  1     181230.0  1.207552e+08    36104459.0
2   3.360100e+10                  1     134969.0  5.566597e+08    39306820.0
3   3.360101e+10                  1      49878.0  4.019932e+08    20327526.0
4   3.360101e+10                  2      37104.0  1.363130e+09    94280527.0

   Social_Media_DL_sum  Social_Media_UL_sum  Youtube_DL_sum  Youtube_UL_sum
0            2206504.0              25631.0      14900201.0       6724347.0
1            2598548.0              62017.0       5324251.0       7107972.0
2            3148004.0              47619.0       2137272.0      19196298.0
3             251469.0              28825.0       4393123.0       2584198.0
4            2861230.0              51312.0      10339971.0      31193031.0

In [34]:
def format_number(df, cols):
    for col in cols:
        df[col] = df.apply(lambda row : f'{row[col]:,.2f}', axis = 1)
    
    return df
    
new_df = format_number(df3, "IMEI")
new_df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,"13,114,483,460,844,900,352.00",4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,"208,201,448,079,117.00","33,664,962,239.00","35,521,209,507,511.00",9.16457E+15,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,"13,114,483,482,878,900,224.00",4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,"208,201,909,211,140.00","33,681,854,413.00","35,794,009,006,359.00",L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,"13,114,483,484,080,500,736.00",4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,"208,200,314,458,056.00","33,760,627,129.00","35,281,510,359,387.00",D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,"13,114,483,485,442,799,616.00",4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,"208,201,402,342,131.00","33,750,343,200.00","35,356,610,164,913.00",T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,"13,114,483,499,480,700,928.00",4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,"208,201,401,415,120.00","33,699,795,932.00","35,407,009,745,539.00",D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [46]:
len(pd.unique(df['Bearer Id']))

134709